LaFacjataExportFacebrick:LaFacjataExportFacebrick.c
	gimptool-2.0 --install LaFacjataExportFacebrick.c
LaFacjataInsertFacebrick:LaFacjataInsertFacebrick.c
	gimptool-2.0 --install LaFacjataInsertFacebrick.c
